name: endvein
description: A lightweight backend for flutter
version: 0.0.1
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  pointycastle: ^3.7.4
  encrypt: ^5.0.3
  asn1lib: ^1.5.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
